# Generated by Django 5.2.4 on 2025-07-12 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewear_app', '0004_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_uploaded', models.PositiveIntegerField(default=0)),
                ('swaps_made', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
