# Generated by Django 5.2.4 on 2025-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewear_app', '0006_user_points_alter_chat_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='Clothing', max_length=50),
        ),
    ]
